export enum SONG_ACTION_TYPES {
    GET_SONGS = "GET_SONGS",
    ADD_SONG = "ADD_SONG",
    DELETE_SONG="DELETE_SONG",
    EDIT_SONG="EDIT_SONG"
}

export enum PLAYLIST_ACTION_TYPES{
    GET_PLAYLISTS = "GET_PLAYLISTS",
    ADD_PLAYLIST = "ADD_PLAYLIST",
    DELETE_PLAYLIST= "DELETE_PLAYLIST",
    UPDATE_PLAYLIST = "UPDATE_PLAYLIST",
}