export enum STUDENT_ACTION_TYPES {
    GET_STUDENTS = "GET_STUDENTS",
    ADD_STUDENTS = "ADD_STUDENT",
    DELETE_STUDENT="DELETE_STUDENT",
    EDIT_STUDENT="EDIT_STUDENT"
}

export enum CLASS_ACTION_TYPES{
    GET_CLASS = "GET_CLASS",
    ADD_CLASS = "ADD_CLASS",
    DELETE_CLASS= "DELETE_CLASS",
    UPDATE_CLASS = "UPDATE_CLASS",
}